"""Benchmark fixtures and real-world dataset adapters for growth-policy research."""

from .causal_evidence import (
    CausalEvidenceBundle,
    CausalOptionEstimate,
    CausalOptionEvidenceProducer,
    EvidenceCaseSpec,
    EvidenceTier,
    StaticCausalOptionEvidenceProducer,
    fixed_reference_estimate,
    preregistered_ope_estimate,
    randomized_targeting_estimate,
)
from .criteo import CriteoUpliftData, load_criteo_uplift
from .kuairand_features import load_kuairand_user_features, load_kuairand_video_features
from .llm_evaluation import (
    CausalOptionEvidence,
    LLMBenchmarkCase,
    LLMCandidateScore,
    LLMDecision,
    LLMExperimentPlan,
    LLMHoldoutResult,
    LLMPolicyCandidate,
    LockedLLMBenchmarkArtifact,
    LockedLLMPolicyProtocol,
    collect_planner_decisions,
    evaluate_llm_candidate,
)
from .llm_shadow_runner import (
    LockedShadowBenchmarkRun,
    ShadowPlannerEntry,
    run_locked_shadow_benchmark,
)
from .locked_evaluation import (
    LockedBenchmarkArtifact,
    LockedOPEProtocol,
    LockedTargetingProtocol,
    OPECandidate,
    OPEHoldoutResult,
    OPEValidationScore,
    TargetingHoldoutResult,
    TargetingValidationScore,
    ope_records_fingerprint,
    targeting_evidence_fingerprint,
    treatment_records_fingerprint,
)
from .ope_evidence_gate import EvidenceGatedOPEProtocol, OPEEvidenceGate
from .offline_rl import (
    HistorySummary,
    OfflineRLDataset,
    OfflineRLTransition,
    default_kuairand_state_builder,
    kuairand_to_offline_rl,
)
from .open_bandit_features import load_open_bandit_item_context
from .open_bandit_ope import open_bandit_to_ope
from .planner_sequences import (
    KuaiRandHistory,
    KuaiRandPlannerRecord,
    default_planner_observation,
    kuairand_to_planner_records,
    kuairand_to_planner_transitions,
)
from .real_world import (
    DEFAULT_KUAIRAND_REWARD_WEIGHTS,
    KuaiRandInteraction,
    OpenBanditInteraction,
    RandomizedTargetingResult,
    evaluate_randomized_targeting,
    kuairand_reward,
    load_kuairand,
    load_open_bandit,
)
from .runner import GrowthAgentBench, PolicyBenchmarkResult
from .splits import DatasetSplit, deterministic_stratified_split, ordered_split
from .statistics import (
    TargetingBootstrapResult,
    TargetingInferenceResult,
    bootstrap_randomized_targeting,
    infer_randomized_targeting,
)
from .synthetic import (
    CATEBenchmarkResult,
    SyntheticGrowthSample,
    evaluate_cate,
    make_synthetic_growth_bandit,
    oracle_policy_value,
)

__all__ = [
    "CATEBenchmarkResult",
    "CausalEvidenceBundle",
    "CausalOptionEstimate",
    "CausalOptionEvidence",
    "CausalOptionEvidenceProducer",
    "CriteoUpliftData",
    "DEFAULT_KUAIRAND_REWARD_WEIGHTS",
    "DatasetSplit",
    "EvidenceCaseSpec",
    "EvidenceGatedOPEProtocol",
    "EvidenceTier",
    "GrowthAgentBench",
    "HistorySummary",
    "KuaiRandHistory",
    "KuaiRandInteraction",
    "KuaiRandPlannerRecord",
    "LLMBenchmarkCase",
    "LLMCandidateScore",
    "LLMDecision",
    "LLMExperimentPlan",
    "LLMHoldoutResult",
    "LLMPolicyCandidate",
    "LockedBenchmarkArtifact",
    "LockedLLMBenchmarkArtifact",
    "LockedLLMPolicyProtocol",
    "LockedOPEProtocol",
    "LockedShadowBenchmarkRun",
    "LockedTargetingProtocol",
    "OPECandidate",
    "OPEEvidenceGate",
    "OPEHoldoutResult",
    "OPEValidationScore",
    "OfflineRLDataset",
    "OfflineRLTransition",
    "OpenBanditInteraction",
    "PolicyBenchmarkResult",
    "RandomizedTargetingResult",
    "ShadowPlannerEntry",
    "StaticCausalOptionEvidenceProducer",
    "SyntheticGrowthSample",
    "TargetingBootstrapResult",
    "TargetingHoldoutResult",
    "TargetingInferenceResult",
    "TargetingValidationScore",
    "bootstrap_randomized_targeting",
    "collect_planner_decisions",
    "default_kuairand_state_builder",
    "default_planner_observation",
    "deterministic_stratified_split",
    "evaluate_cate",
    "evaluate_llm_candidate",
    "evaluate_randomized_targeting",
    "fixed_reference_estimate",
    "infer_randomized_targeting",
    "kuairand_reward",
    "kuairand_to_offline_rl",
    "kuairand_to_planner_records",
    "kuairand_to_planner_transitions",
    "load_criteo_uplift",
    "load_kuairand",
    "load_kuairand_user_features",
    "load_kuairand_video_features",
    "load_open_bandit",
    "load_open_bandit_item_context",
    "make_synthetic_growth_bandit",
    "ope_records_fingerprint",
    "open_bandit_to_ope",
    "oracle_policy_value",
    "ordered_split",
    "preregistered_ope_estimate",
    "randomized_targeting_estimate",
    "run_locked_shadow_benchmark",
    "targeting_evidence_fingerprint",
    "treatment_records_fingerprint",
]
